@baseUrl = https://localhost:5001

GET {{baseUrl}}/WeatherForecast
Accept: application/json

### Separo y sale otro botón "Send Request"
GET {{baseUrl}}/WeatherForecast/1
Accept: application/json

###
POST {{baseUrl}}/api/TodoItems
Accept: application/json
